disabled_rules:
- type_name
- identifier_name
- force_try
- force_cast
- line_length
- cyclomatic_complexity
- for_where
- function_body_length
- file_length
- multiple_closures_with_trailing_closure

opt_in_rules:
- empty_count
- empty_string

excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib
- /Users/liem/Documents/IOS Developer/DailyLifeVesionMVVM/R.generated.swift
reporter: "xcode"
